# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_binary(name='djangoHello_main',
  dependencies=[
    'examples/src/python/djangoHello'
  ],
  source='manage.py',
)
