# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Like Hello world, but built with Pants.

python_library(name='djangoHello',
  dependencies=[
    '3rdparty/python:Django',
  ],
  sources=globs('*.py'),
)
