# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_binary(name='djangoHelloMain',
  dependencies=[
    'examples/src/python/djangoHello',
    '3rdparty/python:Django',
    'examples/src/python/greet:greet'
  ],
  source='manage.py',
)
