# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# The djangoHello library doesn't do much, but we should still test it

python_tests(name='test',
  dependencies=[
    'examples/src/python/djangoHello',
  ],
  sources=globs('*.py'),
)
